<h1 id="top">目錄</h1>

- [1. Exception 例外處裡](#s1)
- [2. 例外的類別層級架構](#s2)
- [3. try-catch](#s3)
- [4. try-catch-finally](#s4)
- [5. throws 關鍵字](#s5)
- [6. 常見的 Runtime Exception](#s6)
- [7. 其他](#s7)

---

# <a id='s1' class='md-title' href='#top'>1. Exception 例外處裡</a>

- 提升 Java 的**穩固**性

- Java 程式執行時，如果發生異常狀況，可以借助例外處裡

  - **程式發生(產生)例外時，視為產生一個 Exception 物件**

- Java 的例外處裡可將一般**正常處裡程序**與**錯誤處裡程序**做到**分開敘述**，讓程式可讀性提高

  - 五個關鍵字: `try`、`catch`、`finally`、`throws`、`throw`

- 適合使用的時機: 如資料庫連結失敗、找不到檔案、除 0、參數為空、參數型態不符、陣列索引超出範圍..等

# <a id='s2' class='md-title' href='#top'>2. 例外的類別層級架構</a>

- Throwable 層級架構

- Throwable
  - Error
    - AssertionError
    - VirtualMachineError
      - StackOverflowError
      - OutOfMemoryError
  - Exception(也是一定要處裡的例外)
    - 不一定要處裡的例外
      - RuntimeException
        - ArithmeticException
        - ClassCastException
        - IndexOutOfBoundsException
          - ArrayIndexOutOfBoundsException
        - IllegalArgumentException
          - NumberFormatException
        - IllegalStateException
        - NullPointerException
        - IllegalMonitorStateException
    - 一定要處裡的例外
      - ParaseException
      - IOException
        - EOFException
        - FileNotFoundException
      - InterruptedException

# <a id='s3' class='md-title' href='#top'>3. try-catch</a>

- Java 的例外處裡

  - `MyException e` ，`MyException` 指定該 catch 要處裡的例外種類(類型)，`e` 對接進來的例外物件的名稱(可自行取名)

  - 每個 catch 就是一種例外處裡方式，所以 catch 可以很多個

  - 例外處裡中，**類別位階高**(父類別)者需置於**類別位階低**(子類別)者**後方**

    - 因為如果位階高的在前方，則後續 catch 則永遠不可能執行到

```java
try{
  正常處裡程序的程式碼...;
} catch(MyException e){
  錯誤處裡程序的程式碼...;
} catch(Exception e){
  錯誤處裡程序的程式碼...;
} ...
```

- 例外用法

```java
package ch01;

public class TestTryCatch {
  public static void main(String[] args) {
    int i = 0;
    String[] strs = { "1", "2", "Hello3" };
    while (i < 4) {
      try {
        System.out.println(Integer.parseInt(strs[i]));
      } catch (ArrayIndexOutOfBoundsException e) {
        System.out.println(e);
      } catch (Exception e) {
        System.out.println(e);
      } catch (Throwable e) {
        System.out.println(e);
      }
      i++;
    }
    System.out.println(i);
  }
}
```

---

```java
1
2
java.lang.NumberFormatException: For input string: "Hello3"
java.lang.ArrayIndexOutOfBoundsException: 3
4
```

# <a id='s4' class='md-title' href='#top'>4. try-catch-finally</a>

- 將一定要執行的程式碼放在 finally{}的程式區塊裡

- finally{} 是無論發生什麼情況皆會執行的程式區塊，用來釋放有限的資源，如: 關閉(close)資料庫連線、檔案讀取...等

  ```java
  try{
    正常處裡程序的程式碼...;
  } catch(MyException e){
    錯誤處裡程序的程式碼...;
  } catch(Exception e){
    錯誤處裡程序的程式碼...;
  } finally {
    一定要執行的程式碼...;
  }
  ```

- 例外用法

  ```java
  package ch01;

  public class TestTryCatchFinally {
    public static void main(String[] args) {
      int i = 0;
      String[] strs = { "Hello1", "Hello2", "Hello3" };
      while (i < 4) {
        try {
          System.out.println(strs[i]);
        } catch (ArrayIndexOutOfBoundsException e) {
          System.out.println("1-已超出陣列的長度");
        } catch (Exception e) {
          System.out.println("2-發生Exception");
        } finally {
          System.out.println("一定要執行的程式碼");
        }
        i++;
      }
      System.out.println("---------------------------");
      while (i < 5) {
        try {
          System.out.println(strs[i]);
        } catch (IllegalStateException e) {
          System.out.println("1-已超出陣列的長度");
        } finally {
          System.out.println("一定要執行的程式碼");
        }
        i++;
      }
    }
  }
  ```

  ***

  ```java
  Hello3
  一定要執行的程式碼
  1-已超出陣列的長度
  一定要執行的程式碼
  ---------------------------
  一定要執行的程式碼
  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
    at ch01.TestTryCatchFinally.main(TestTryCatchFinally.java:23)
  ```

# <a id='s5' class='md-title' href='#top'>5. throws 關鍵字</a>

- Java 有兩種不同型態的例外(Exceptions)

  - **執行時期的例外**

    - 這一類的例外不一定要處裡

    - 也稱為不必檢查的例外(`unchecked exceptions`)

    - 如 `Runtime Exception` 及其**子類別**

  - **非執行時期的例外**

    - 這一類的例外一定要**處裡**

    - 也稱為必須檢查的例外(`checked exceptions`)

    - 如 `IOException` 、 `SQLException` ...等

- 在方法定義時，可使用 `throws` 關鍵字將可能發生的例外，丟出給呼叫此方法的程式去處裡(例外可以一直丟，最後會是 JVM 執行，說明錯誤原因並停止程式運行)

  - void method() throws MyExcetion {...}

  - public static int parseInt(String s) throws NumberFormatException {...}

  - public int read() throws IOException {...}

  - public static Connection getConnection() throws SQLException

- 對於`checked exceptions`，在呼叫有 `throws` 關鍵字的方法時，**必須**將該方法置於下列兩者之一

  - 將該方法至於 try {} 程式區塊中

    - try...catch **明確處裡**(自己抓下來做處裡動作)

  - (或)將該方法置於定義有 throws 關鍵字的方法中

    - 此為在透過 throws 丟出例外，然後再由下一個呼叫者來處裡

    - throws **消極處裡**(再丟改後面的使用者去處裡)

- 一定要處裡的例外做法 1: 明確處裡

  ```java
  package ch01;

  public class TestThrows1 {
    String[] strs = { "Hello1", "Hello2", "Hello3" };

    // Exception 是一定要處裡的例外，所以要用 try...catch 處裡
    public void printStrs(int i) throws Exception {
      System.out.println(strs[i]);
    }

    public static void main(String[] args) {
      int i = 0;
      TestThrows1 t1 = new TestThrows1();
      while (i < 4) {
        try {
          t1.printStrs(i);
        } catch (ArrayIndexOutOfBoundsException e) {
          System.out.println("1-已超出陣列的長度");
        } catch (Exception e) {
          System.out.println("2-發生Exception");
        }
        i++;
      }
    }
  }
  ```

  ***

  ```java
  Hello1
  Hello2
  Hello3
  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
    at ch01.TestThrows1.printStrs(TestThrows1.java:7)
    at ch01.TestThrows1.main(TestThrows1.java:14)
  ```

- 一定要處裡的例外做法 2: 消極處裡

  ```java
  package ch01;

  public class TestThrows2 {
    String[] strs = { "Hello1", "Hello2", "Hello3" };

    // 2. 不處裡例外
    public void printStrs(int i) throws Exception {
      System.out.println(strs[i]);
    }

    // 4. 沒人要處裡例外，拋出由JVM處裡
    public static void main(String[] args) throws Exception {
      int i = 0;
      TestThrows2 t2 = new TestThrows2();
      while (i < 4) {
        // 1. 執行
        t2.printStrs(i);
        // 3. 不處理例外
        i++;
      }
    }
  }
  ```

  ***

  ```cs
  Hello1
  Hello2
  Hello3
  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
    at ch01.TestThrows2.printStrs(TestThrows2.java:7)
    at ch01.TestThrows2.main(TestThrows2.java:14)
  ```

- 不一定要處裡的例外作法

  ```java
  package ch01;

  public class TestThrows1 {
    String[] strs = { "Hello1", "Hello2", "Hello3" };

    // ArrayIndexOutOfBoundsException 是不一定要處裡的例外，所以不用 try...catch 處裡也行
    public void printStrs(int i) throws ArrayIndexOutOfBoundsException {
      System.out.println(strs[i]);
    }

    public static void main(String[] args) {
      int i = 0;
      TestThrows1 t1 = new TestThrows1();
      while (i < 4) {
        t1.printStrs(i);
        i++;
      }
    }
  }
  ```

# <a id='s6' class='md-title' href='#top'>6. 常見的 Runtime Exception</a>

- <table>
  <thead>
  <tr>
  <th style="text-align:center">例外(Exception)的類別名稱</th>
  <th>例外狀況說明</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td style="text-align:center">ArithmeticException</td>
  <td>分母為 0 時</td>
  </tr>
  <tr>
  <td style="text-align:center">NullPointerException</td>
  <td>呼叫到一個空值 null 變數</td>
  </tr>
  <tr>
  <td style="text-align:center">IlleggalArgumentException</td>
  <td>傳入的參數型態不符</td>
  </tr>
  <tr>
  <td style="text-align:center">NumberFormateException</td>
  <td>傳入的參數型態不符(前者的子類別)</td>
  </tr>
  <tr>
  <td style="text-align:center">IndexOutOfBoundsException</td>
  <td>索引值超過物件上限</td>
  </tr>
  <tr>
  <td style="text-align:center">ArrayIndexOutOfBoundsException</td>
  <td>索引值超過陣列上限(前者的子類別)</td>
  </tr>
  <tr>
  <td style="text-align:center">SecurityException</td>
  <td>違反安全原則(ex.將 package 命名成 java)</td>
  </tr>
  </tbody>
  </table>

# <a id='s7' class='md-title' href='#top'>7. 其他</a>

- final 修飾關鍵字

  - **變量**上面不能修改變量，也不能指向新對象
  - **方法**上面不能被修改方法
  - **類別**上面不能被繼承

- finalize

  - 給垃圾回收呼叫的

- filally

  - 是個關鍵字，用在例外執行上

---

參考鏈接

- [浅析 Java 中的 final 关键字](https://www.cnblogs.com/dolphin0520/p/3736238.html)
- [Java 关键字 final 使用详解](https://blog.csdn.net/a13429921973/article/details/12885885)
